export const GET_DATA_REQUEST = 'GET_DATA_REQUEST'
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS'
export const GET_DATA_FAILURE = 'GET_DATA_FAILURE'

export const SORT_DATA_REQUEST = 'SORT_DATA_REQUEST'
export const SORT_DATA_SUCCESS = 'SORT_DATA_SUCCESS'
export const SORT_DATA_FAILURE = 'SORT_DATA_FAILURE'
